int read_parameters(char param_file_name[]);
int readBinaryFile();
double sinc(double x);
double W_NGP(double k);
double W_CIC(double k);
double W_TSC(double k);
double W_D20_Re(double k);
double W_D20_Im(double k);
double zero(double k);
double Sum_W2_NGP(double k);
double Sum_W2_CIC(double k);
double Sum_W2_TSC(double k);
double Sum_W2_D20(double k);
